lsコマンドを作るオブジェクト指向版 の課題提出
88-99/fbc-ruby-practices pull request #12
Opened 2023-05-07 11:07 UTC by 88-99

課題を実装しました。
ご確認お願いいたします。

#### 終了条件
- lsコマンドのプログラムをオブジェクト指向で書いてPull RequestとしてアップしてそのURLとTerminalでの実行結果を提出しよう。（OS標準のlsコマンドの実行結果もあわせて載せること）
- rubocop-fjord のチェックが全てパスしたこともスクショで貼り付ける。
どうしても解決できない警告があれば、その理由を書くこと。

2023-05-13 01:38 UTC, u1tnk requested changes
基本的なクラスの使い方はできてるようですね 👍 

まずはクラスの分け方を見直してください。
LSクラスが重いので分量のある機能のlオプションを分けた、という観点では業務なのではおかしくは無いものの、オブジェクト指向の練習としては良くないです。

分け方に決まりはありませんが、表示や情報収集など機能単位で分けるのがやりやすいと思います。

補足するとこのプラクティスでは存在しませんが、LオプションクラスがやっていることはLオプションのときの表示であり、例えば lsの hオプションなど表示を調整するオプションが追加で指摘されたときにこの構造だと表現できないと思います。

また、メソッド名の指摘にもあるようにオブジェクト指向の目的としてクラスという部品を使いやすくしたいというのがあるので、コードが読みやすい、分かりやすいというのも意識して欲しいと思います。

2023-05-13 01:38 UTC, u1tnk commented on 08.ls_object/lib/ls.rb
> +  attr_reader :argv_option, :filenames
外部からアクセスされない変数を attr_readerを使うのはカプセル化の観点からNGです。
同じクラス内からは単に `@hoge` で大丈夫です。

2023-05-13 01:38 UTC, u1tnk commented on 08.ls_object/lib/ls.rb
> +      puts lop.l_option
一般的に クラスは名詞、メソッドは動詞(データを返すだけのものは名詞)となり、英語としてなんとなく意味が通じる(もちろん完全に英語では無いです)という状態にして欲しいです。

この状態だと「 lオプションのlオプション」になってしまい、何をしているのか推測できません。

2023-05-17 11:12 UTC, 88-99 commented on 08.ls_object/lib/ls.rb
> +  attr_reader :argv_option, :filenames
ありがとうございます。修正しました。

2023-05-17 11:13 UTC, 88-99 commented on 08.ls_object/lib/ls.rb
> +      puts lop.l_option
ありがとうございます。修正しました。

2023-05-21 15:24 UTC, u1tnk requested changes
だいぶ良くなってきました！
もう少しクラスの責務を考えて適切な場所に配置できると良いですね。

2023-05-21 15:24 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def initialize(options)
せっかく ls.rbでは option一個ずつ渡してるのに受け取り側でまとめてしまうとこのクラスで何のオプションを使うのか分からなくなってしまうので一つづつ持ちましょう。
まが、 option_longを渡しているようですが必要でしょうか？

2023-05-21 15:24 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def transpose_safely
このメソッドは目的からすると NormalFormatterでやるべきかと思います。

2023-05-21 15:24 UTC, u1tnk commented on 08.ls_object/lib/file_list.rb
> +  def refer_file_items
単にfile_itemsを返すだけなら attr_readerで良いと思います。

2023-05-21 15:24 UTC, u1tnk commented on 08.ls_object/lib/long_formatter.rb
> +    ["total #{@file_items.map(&:blocks).sum}", build_row_long_option]
FileListはファイルを全部持っているので 計算はそちらでやるようにしましょう

2023-05-21 15:24 UTC, u1tnk commented on 08.ls_object/lib/long_formatter.rb
> +  def build_row_long_option
ここはLongFormatterなので long_option という名前は冗長です。

2023-05-21 15:24 UTC, u1tnk commented on 08.ls_object/lib/long_formatter.rb
> +    array.max.to_s.length
この計算もFileListでやるべきです。

2023-05-23 15:01 UTC, 88-99 commented on 08.ls_object/lib/file_list.rb
> +  def initialize(options)
ありがとうございます。修正しました。
`def initialize(option_all:, option_reverse:)`

option_longはここでは必要ありませんでした。

2023-05-23 15:05 UTC, 88-99 commented on 08.ls_object/lib/file_list.rb
> +  def transpose_safely
移動しました。
目的は、「フォーマットに適した配列を作っている」ので、NormalFormatterでやるべきなのでしょうか？

2023-05-23 15:09 UTC, 88-99 commented on 08.ls_object/lib/file_list.rb
> +  def refer_file_items
かしこまりました。ありがとうございます。

2023-05-23 15:13 UTC, 88-99 commented on 08.ls_object/lib/long_formatter.rb
> +    ["total #{@file_items.map(&:blocks).sum}", build_row_long_option]
修正しました。
FileListクラスで計算したものは、LongFormatterの初期化時に引数で渡していますがいかがでしょうか？

2023-05-23 15:15 UTC, 88-99 commented on 08.ls_object/lib/long_formatter.rb
> +  def build_row_long_option
long_optionを消してbuild_rowのみにしました。

`def build_row`

2023-05-23 15:18 UTC, 88-99 commented on 08.ls_object/lib/long_formatter.rb
> +    array.max.to_s.length
`file_list.find_max_nlink, file_list.find_max_size`別々に計算して、LongFomatterの初期化時にそれぞれ引数で渡すようにしてみました。

2023-05-23 17:30 UTC, u1tnk requested changes
大体大丈夫ですが細かいところコメントしました！

2023-05-23 17:30 UTC, u1tnk commented on 08.ls_object/lib/ls.rb
> +                  LongFomatter.new(file_list.file_items, file_list.calc_total_file_blocks, file_list.find_max_nlink, file_list.find_max_size).format
NormalFormatterだと filenamesしか使わないので限定した方が良いですが、LongFormatterの方はほとんど使う上、file_listが全て持っているので file_listを渡した方がスッキリすると思います。

2023-05-23 17:30 UTC, u1tnk commented on 08.ls_object/lib/ls.rb
> +                  # NomalFomatter.new(filenames.transpose_safely).format
コメントアウトしたものは理由が無ければコミットしないようにしましょう

2023-05-23 17:30 UTC, u1tnk commented on 08.ls_object/lib/nomal_formatter.rb
> +    1.upto(NUMBER_OF_COLUMNS - 1).to_a
この NUMBER_OF_COLUMNSは別ファイルのものなのでこのクラス内にあった方が良いと思います。

2023-05-23 17:30 UTC, u1tnk commented on 08.ls_object/lib/nomal_formatter.rb
> +      @filenames.each_slice(quotient + 1).to_a.transpose
小ネタですけど `.to_a.transpose` は共通してるので、 ifの戻り値を変数に入れるか直接 以下のようにするとちょっとスッキリしますね。若干読みづらくなるので、一回変数に代入した方が無難な気はしますが、良い変数名が思いつかなければendの後にするかなー  🤔 

```
if 
  ...
end.to_a.transpose
```

2023-05-23 17:30 UTC, u1tnk commented on 08.ls_object/lib/nomal_formatter.rb
> +    1.upto(NUMBER_OF_COLUMNS - 1).to_a
そもそも 呼ばれてるところは each呼んでるので to_a は不要そうですね。そうなるとメソッドにするほどでも無さ

2023-05-24 13:57 UTC, 88-99 commented on 08.ls_object/lib/ls.rb
> +                  # NomalFomatter.new(filenames.transpose_safely).format
消し忘れました。すみません🙇‍♂️

2023-05-24 14:12 UTC, 88-99 commented on 08.ls_object/lib/nomal_formatter.rb
> +    1.upto(NUMBER_OF_COLUMNS - 1).to_a
> この NUMBER_OF_COLUMNSは別ファイルのものなのでこのクラス内にあった方が良いと思います。

ご指摘ありがとうございます！そうでした。
to_aを消したときの値を確認したいと思いデバッグすると`#<Enumerator: ...>`が表示されるのですが、これは何を表していますでしょうか？

```
=>  14|   debugger
    15|     1.upto(NUMBER_OF_COLUMNS - 1)
    16|   end
    17|
    18|   def find_max_character_number
=>#0	NomalFomatter#determine_row_indexes at ~/bin/fbc-ruby-practices/08.ls_object/lib/nomal_formatter.rb:14
  #1	block {|row=["file_item.rb", "long_formatter.rb", "no...|} in format at ~/bin/fbc-ruby-practices/08.ls_object/lib/nomal_formatter.rb:37
  # and 4 frames (use `bt' command for all frames)
(ruby) 1.upto(NUMBER_OF_COLUMNS - 1)
#<Enumerator: ...>
(ruby) 1.upto(2)
#<Enumerator: ...>
```

ブロックに渡してprintすると値が確認できることはわかります。
5.upto(10) {|i| print i, " " } # => 5 6 7 8 9 10
https://docs.ruby-lang.org/ja/latest/method/Integer/i/upto.html

2023-05-24 14:14 UTC, 88-99 commented on 08.ls_object/lib/nomal_formatter.rb
> +    1.upto(NUMBER_OF_COLUMNS - 1).to_a
> この NUMBER_OF_COLUMNSは別ファイルのものなのでこのクラス内にあった方が良いと思います。

ご指摘ありがとうございます！そうでした。
to_aを消したときの値を確認したいと思いデバッグすると`#<Enumerator: ...>`が表示されるのですが、これは何を表していますでしょうか？

```
=>  14|   debugger
    15|     1.upto(NUMBER_OF_COLUMNS - 1)
    16|   end
    17|
    18|   def find_max_character_number
=>#0	NomalFomatter#determine_row_indexes at fbc-ruby-practices/08.ls_object/lib/nomal_formatter.rb:14
  #1	block {|row=["file_item.rb", "long_formatter.rb", "no...|} in format at fbc-ruby-practices/08.ls_object/lib/nomal_formatter.rb:37
  # and 4 frames (use `bt' command for all frames)
(ruby) 1.upto(NUMBER_OF_COLUMNS - 1)
#<Enumerator: ...>
(ruby) 1.upto(2)
#<Enumerator: ...>
```

ブロックに渡してprintすると値が確認できることはわかります。
5.upto(10) {|i| print i, " " } # => 5 6 7 8 9 10
https://docs.ruby-lang.org/ja/latest/method/Integer/i/upto.html

2023-05-24 14:48 UTC, 88-99 commented on 08.ls_object/lib/nomal_formatter.rb
> +      @filenames.each_slice(quotient + 1).to_a.transpose
> ifの戻り値を変数に入れるか直接 以下のようにするとちょっとスッキリしますね。

ありがとうございます。each_sliced_filenamesはいかがでしょうか...
```
each_sliced_filenames = if remainder != 0
                          (NUMBER_OF_COLUMNS - remainder).times { @filenames << nil }
                          @filenames.each_slice(quotient + 1)
                        else
                          @filenames.each_slice(quotient)
                        end
each_sliced_filenames.to_a.transpose
```

2023-05-24 15:34 UTC, 88-99 commented on 08.ls_object/lib/nomal_formatter.rb
> +    1.upto(NUMBER_OF_COLUMNS - 1).to_a
ありがとうございます。修正しました。to_a は不要でした。

2023-05-24 15:40 UTC, 88-99 commented on 08.ls_object/lib/ls.rb
> +                  LongFomatter.new(file_list.file_items, file_list.calc_total_file_blocks, file_list.find_max_nlink, file_list.find_max_size).format
LongFormatterクラスにfile_listを渡して、LongFormatterクラス内でfile_list.メソッドの形で使えるようにしてみました。この方法はいかがでしょうか？
```
class FileList
  attr_reader :filenames, :file_items, :total_file_blocks, :max_nlink, :max_size

  def initialize(option_all:, option_reverse:)
    @option_all = option_all
    @option_reverse = option_reverse
    @filenames = fetch_files
    @file_items = fetch_files.map { FileItem.new(_1) }
    @total_file_blocks = calc_total_file_blocks
    @max_nlink = find_max_nlink
    @max_size = find_max_size
  end
```

2023-05-24 16:39 UTC, u1tnk approved these changes
👍

2023-07-06 13:25 UTC, merged